---
title: "Lab_2"
author: "Jake Austin Kistler"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tasks

## task 1:
Get the working directory for this lab:
````{r}
getwd()
````

## Task 2:
Save the data file as a CSV, open it and read the first 6 rows from it.
````{r}
# Read the data into a data frame (df) using read.csv()
dat <- read.csv("EPAGAS-1.XLS - Sheet1.csv")

# Use head to display the first 6 rows of data
head(dat,6)
````

## Task 3:
Make the object mpg and populate it with the MPG from the data file
````{r}
# make and assign the object data
mpg = dat$MPG
mpg
````
Now to transform mpg into z 
````{r}
# this calculation was shown in class and is in the given example code
z <- (mpg - mean(mpg)) / sd(mpg)
z
````

finding both the outliners and the potential outliners 
````{r}
# R allows for c-like loops:https://www.statology.org/how-to-vectorize-in-r-with-example/

# we want to store both types of outliers so vectors for both
outliers <- c()
possible_outliers <- c()

for(i in 1:length(z)) # this gets us the length of elements in z this is like the standard for loop header in c but we start at 1 and not 0
{
  if(abs(z[i]) > 3) # make the comparison for 100% these are outliners 
  {
    outliers <- c(outliers, i) # this is like vect.push_back in cpp we just add data to the vector
  }
  else if(abs(z[i]) > 2) # make the check for possible outliners
  {
    possible_outliers <- c(possible_outliers, i) # append to the vector these values
  }
}
````
 Now to display both vecs:
````{r}
outliers
possible_outliers
````


